# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  github_user: '%env(GITHUB_USER)%'
  github_token: '%env(GITHUB_TOKEN)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Controllers
  Jcv\DeveloperHub\Ui\API\:
    resource: '../../../src/DeveloperHub/Ui/API'
    tags: [ 'controller.service_arguments' ]

  # Controllers
  Jcv\DeveloperHub\Ui\Web\:
    resource: '../../../src/DeveloperHub/Ui/Web'
    tags: [ 'controller.service_arguments' ]

  # Commands
  Jcv\DeveloperHub\Ui\CLI\:
    resource: '../../../src/DeveloperHub/Ui/CLI'
    tags: [ 'console.command' ]

  use_cases:
    namespace: Jcv\DeveloperHub\Application\
    resource: '../../../src/DeveloperHub/Application/**/*{UseCase.php}'
    tags: [ use_cases ]
    public: true

  domain_services:
    namespace: Jcv\DeveloperHub\Domain\Service\
    resource: '../../../src/DeveloperHub/Domain/Service/*'
    tags: [ domain_services ]

  # Developer finder
  Jcv\DeveloperHub\Domain\Service\Developer\DeveloperFinder:
    alias: Jcv\DeveloperHub\Infrastructure\Domain\Service\Developer\GitHubDeveloperFinder

  # Github developer finder
  Jcv\DeveloperHub\Infrastructure\Domain\Service\Developer\GitHubDeveloperFinder:
    class: Jcv\DeveloperHub\Infrastructure\Domain\Service\Developer\GitHubDeveloperFinder
    arguments: [ '%github_user%', '%github_token%' ]
