version: "3.4"

services:
  composer:
    image: composer

  phpunit:
    image: php:7.4
    volumes:
      - ./:/app
    working_dir: /app
    command: php -S localhost:8000

  developer-hub:
    image: colvin-developer-hub
    build:
      context: .
      dockerfile: ./applications/developer-hub/Dockerfile
    volumes:
      - ./:/var/www/html/devhub
    ports:
      - "${DEVELOPER_HUB_WEB_PORT}:80"
    environment:
      - PORT=80
